  version: '3.3'

  services:
   atelierchilaze:
     container_name: atelierchilaze
     image: wordpress:php7.2-apache
     expose:
       - 80
     volumes:
       - /var/www/html/atelierchilaze:/var/www/html/
     restart: always
     environment:
       VIRTUAL_HOST: atelierchilaze.com.br
       WORDPRESS_DB_HOST: 172.31.59.231:3306
       WORDPRESS_DB_USER: atelierchilaze_prod
       WORDPRESS_DB_PASSWORD: 8vR4Feb9acuZCRH6
       WORDPRESS_DB_NAME: atelierchilaze_prod 
       CERT_NAME: atelierchilaze
  networks:
    default:
      external:
        name: docker01
