  version: '3.3'

  services:
    dev.i9b2:
     container_name: dev.i9b2
     image: wordpress:php7.4-apache
     expose:
       - 80
     volumes:
       - /var/www/html/dev.i9b2:/var/www/html/
     restart: always
     environment:
       VIRTUAL_HOST: i9b2.brtloja.com.br
       WORDPRESS_DB_HOST: 172.31.59.231:3306
       WORDPRESS_DB_USER: bertholdo_db
       WORDPRESS_DB_PASSWORD: brtdba@3
       WORDPRESS_DB_NAME: dev.i9b2
       CERT_NAME: brtloja
  networks:
    default:
      external:
        name: docker01
