  version: '3.3'

  services:
    editoramonolito:
     container_name: editoramonolito
     image: brt.editoramonolito:prod
     expose:
       - 80
     volumes:
       - /var/www/html/editoramonolito:/var/www/html/
     restart: always
     environment:
       VIRTUAL_HOST: editoramonolito.com.br
       WORDPRESS_DB_HOST: 172.31.59.231:3306
       WORDPRESS_DB_USER: monolito_prod
       WORDPRESS_DB_PASSWORD: s8xd4t7NXsBYYHkJ
       WORDPRESS_DB_NAME: monolito_prod
       CERT_NAME: editoramonolito 
  networks:
    default:
      external:
        name: docker01
