  version: '3.3'

  services:
    i9b2:
     container_name: i9b2
     image: brt.i9b2:prod
     expose:
       - 80
     volumes:
       - /var/www/html/i9b2:/var/www/html/
     restart: always
     environment:
       VIRTUAL_HOST: i9b2.com.br
       WORDPRESS_DB_HOST: 172.31.59.231:3306
       WORDPRESS_DB_USER: i9b2
       WORDPRESS_DB_PASSWORD: QV%%CP6=<Hus
       WORDPRESS_DB_NAME: i9b2
       CERT_NAME: i9b2
  networks:
    default:
      external:
        name: docker01
